### ISSUE TITLE
Receive: ServerInfo in loop

### ISSUE THREAD

**Issue by Samael-dev** [Kongchenglige/bondage-club_bot#1]
![image](https://github.com/IaSoC/bondage-club_bot/assets/170186291/ff9aae1f-45fd-44eb-9464-ad23230a23b3)
I definitly can't go through this loop and my bot not connect ..

**Comment by Kongchenglige** [comment]
Hi, this project is not under maintenance, because I haven't played the game for a long time.

TLDR: You need to run both parts(PHP, Python) to let your account link to the server.

the problem here is that this project uses 2 parts to connect the server,
Part 1 is the  Python(which is shown in the screenshot) part, it is used for converse socket.io to the WebSocket, PHP can easier 
 deal with it.
Part 2 is the PHP part, the bot's main program is in there and you can modify it by yourself as you like.(or use other language to reprogram it)

**Comment by Samael-dev** [comment]
Silly question but how run the second part run NGINX put it on enables-sites (cp) main.php and open the link on my web browser ?

**Comment by Kongchenglige** [comment]
You dont need an NGINX to run it, it is a CLI program, just use `php main.php` to run it, like Python.

**Comment by Samael-dev** [comment]
Funny because no directory called vendor >.<
```
PHP Warning:  require_once(/home/nora/bondage-club_bot-Dev/php/vendor/autoload.php): Failed to open stream: No such file or directory in /home/nora/bondage-club_bot-Dev/php/main.php on line 5
PHP Fatal error:  Uncaught Error: Failed opening required '/home/nora/bondage-club_bot-Dev/php/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/nora/bondage-club_bot-Dev/php/main.php:5
Stack trace:
#0 {main}
  thrown in /home/nora/bondage-club_bot-Dev/php/main.php on line 5
```

**Comment by Kongchenglige** [comment]
Oh sorry, I forget to mention it.
Like Python's PIP, PHP also has a package manager called [Composer](https://getcomposer.org/)
for this project, you need to install it to get the package that is required. [how to use](https://getcomposer.org/doc/01-basic-usage.md)

**Comment by Samael-dev** [comment]
Yeah have notice that, my bad for composer is my fault lmfao but have found an issue on your code.
`require_once __DIR__ . '/vendor/autoload.php';` to `require_once __DIR__ . '/../vendor/autoload.php';` for **avoid this :** 
![image](https://github.com/IaSoC/bondage-club_bot/assets/170186291/8d17fd91-0704-4a88-b07c-1d673682dc27)

**Comment by Samael-dev** [comment]
And another issue on your PHP is seem : 
![image](https://github.com/IaSoC/bondage-club_bot/assets/170186291/b7152d74-fe40-418c-b65a-28b5b1e3ddfc)

**Python Log :**

```
connected to socket.io server
Receive: ServerInfo
Receive: ServerInfo
Receive: ServerInfo
Receive: ServerInfo
Receive: ServerInfo
disconnected from socket.io server
Traceback (most recent call last):
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 75, in <module>
    asyncio.run(start_server())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 29, in start_server
    await sio.wait()
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 185, in wait
    await self.sleep(1)  # give the reconnect task time to start up
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 346, in sleep
    return await self.eio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/engineio/async_client.py", line 195, in sleep
    return await asyncio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 639, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
(websockets-client) nora:bondage-club_bot-Dev/ (master✗) $                                                                                                                                               [13:47:02]
(websockets-client) nora:bondage-club_bot-Dev/ (master✗) $ st.sh                                                                                                                                         [13:47:03]
zsh: command not found: st.sh
(websockets-client) nora:bondage-club_bot-Dev/ (master✗) $                                                                                                                                               [13:47:11]
(websockets-client) nora:bondage-club_bot-Dev/ (master✗) $ sh st.sh                                                                                                                                      [13:47:14]
connected to socket.io server
Receive: ServerInfo
New client connected
Sent: AccountLogin
Receive: LoginResponse
WARNING:websocket_server.websocket_server:Client must always be masked.
Client disconnected and service will shutdown,please setup a autorestart bash.
disconnected from socket.io server
New client connected
OverConnect, shutdown.
Client disconnected and service will shutdown,please setup a autorestart bash.
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 47944)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
ERROR:asyncio:Exception in callback Future.set_result(None)
handle: <Handle Future.set_result(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 29, in start_server
    await sio.wait()
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 185, in wait
    await self.sleep(1)  # give the reconnect task time to start up
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 346, in sleep
    return await self.eio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/engineio/async_client.py", line 195, in sleep
    return await asyncio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 639, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
  File "/usr/local/lib/python3.11/dist-packages/websocket_server/websocket_server.py", line 271, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<async_signal_handler.<locals>._handler() running at /usr/local/lib/python3.11/dist-packages/engineio/async_client.py:39> wait_for=<_GatheringFuture finished result=[CancelledError('')]>>
  File "/usr/local/lib/python3.11/dist-packages/websocket_server/websocket_server.py", line 284, in handle
    self.read_next_message()
  File "/usr/local/lib/python3.11/dist-packages/websocket_server/websocket_server.py", line 341, in read_next_message
    opcode_handler(self, message_bytes.decode('utf8'))
  File "/usr/local/lib/python3.11/dist-packages/websocket_server/websocket_server.py", line 163, in _message_received_
    self.message_received(self.handler_to_client(handler), self, msg)
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 63, in message_received
    asyncio.run(sio.emit(msg[0],msg[1]))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 220, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 29, in start_server
    await sio.wait()
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 185, in wait
    await self.sleep(1)  # give the reconnect task time to start up
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 346, in sleep
    return await self.eio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/engineio/async_client.py", line 195, in sleep
    return await asyncio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 639, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 75, in <module>
    asyncio.run(start_server())
  File "/usr/lib/python3.11/asyncio/runners.py", line 189, in run
    with Runner(debug=debug) as runner:
  File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__
    self.close()
  File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close
    loop.run_until_complete(loop.shutdown_default_executor())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 573, in shutdown_default_executor
    await future
asyncio.exceptions.CancelledError
----------------------------------
AutoRestartBash:Restarting...
connected to socket.io server
Receive: ServerInfo
New client connected
Sent: AccountLogin
Receive: LoginResponse
WARNING:websocket_server.websocket_server:Client must always be masked.
Client disconnected and service will shutdown,please setup a autorestart bash.
disconnected from socket.io server
New client connected
OverConnect, shutdown.
Client disconnected and service will shutdown,please setup a autorestart bash.
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 52452)
Traceback (most recent call last):
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 75, in <module>
    asyncio.run(start_server())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 29, in start_server
    await sio.wait()
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 185, in wait
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.11/dist-packages/websocket_server/websocket_server.py", line 271, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/local/lib/python3.11/dist-packages/websocket_server/websocket_server.py", line 284, in handle
    self.read_next_message()
  File "/usr/local/lib/python3.11/dist-packages/websocket_server/websocket_server.py", line 341, in read_next_message
    opcode_handler(self, message_bytes.decode('utf8'))
  File "/usr/local/lib/python3.11/dist-packages/websocket_server/websocket_server.py", line 163, in _message_received_
    self.message_received(self.handler_to_client(handler), self, msg)
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 63, in message_received
    asyncio.run(sio.emit(msg[0],msg[1]))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 220, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
----------------------------------------
    await self.sleep(1)  # give the reconnect task time to start up
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 346, in sleep
    return await self.eio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/engineio/async_client.py", line 195, in sleep
    return await asyncio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 639, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
----------------------------------
AutoRestartBash:Restarting...
connected to socket.io server
Receive: ServerInfo
New client connected
Sent: AccountLogin
WARNING:websocket_server.websocket_server:Client must always be masked.
Client disconnected and service will shutdown,please setup a autorestart bash.
disconnected from socket.io server
Traceback (most recent call last):
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 75, in <module>
    asyncio.run(start_server())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 29, in start_server
    await sio.wait()
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 185, in wait
    await self.sleep(1)  # give the reconnect task time to start up
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 346, in sleep
    return await self.eio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/engineio/async_client.py", line 195, in sleep
    return await asyncio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 639, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
----------------------------------
AutoRestartBash:Restarting...
connected to socket.io server
Receive: ServerInfo
^Cdisconnected from socket.io server
Traceback (most recent call last):
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 75, in <module>
    asyncio.run(start_server())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nora/bondage-club_bot-Dev/proxy.py", line 29, in start_server
    await sio.wait()
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 185, in wait
    await self.sleep(1)  # give the reconnect task time to start up
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/async_client.py", line 346, in sleep
    return await self.eio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/engineio/async_client.py", line 195, in sleep
    return await asyncio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 639, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

**PHP Log :**

```
Workerman[main.php] start in DEBUG mode
------------------------------------------- WORKERMAN --------------------------------------------
Workerman version:4.1.15          PHP version:8.3.7           Event-Loop:\Workerman\Events\Select
-------------------------------------------- WORKERS ---------------------------------------------
proto   user            worker          listen          processes    status
tcp     nora            none            none            1             [OK]
--------------------------------------------------------------------------------------------------
Press Ctrl+C to stop. Start success.
TypeError: Cannot access offset of type string on string in /home/nora/bondage-club_bot-Dev/php/main.php:89
Stack trace:
#0 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Connection/TcpConnection.php(646): {closure}()
#1 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Events/Select.php(311): Workerman\Connection\TcpConnection->baseRead()
#2 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(1638): Workerman\Events\Select->loop()
#3 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#4 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#5 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(560): Workerman\Worker::forkWorkers()
#6 /home/nora/bondage-club_bot-Dev/php/main.php(674): Workerman\Worker::runAll()
#7 {main}
worker[none:24398] exit with status 64000
TypeError: Cannot access offset of type string on string in /home/nora/bondage-club_bot-Dev/php/main.php:89
Stack trace:
#0 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Connection/TcpConnection.php(646): {closure}()
#1 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Events/Select.php(311): Workerman\Connection\TcpConnection->baseRead()
#2 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(1638): Workerman\Events\Select->loop()
#3 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#4 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#5 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#6 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#7 /home/nora/bondage-club_bot-Dev/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#8 /home/nora/bondage-club_bot-Dev/php/main.php(674): Workerman\Worker::runAll()
#9 {main}
worker[none:24400] exit with status 64000
Workerman[main.php] stopping ...
Workerman[main.php] has been stopped
```

**Comment by Kongchenglige** [comment]
So glad to know you successfully fixed the problem.
but sadly the problem seems not caused by my code but by the frame (workerman)
and I can't diagnose by the log, I advise you can try to capture the package to fix it.
Also, I need to note that the code is designed for R7x but not today's server, although I think it won't be so different, but maybe the new function of the game may cause this problem.

I think the Python part didn't need to mention because is just like a Proxy.

**Comment by Samael-dev** [comment]
Hmm I see but what is R7x ? Haven't found anything related to that on Google. **EDIT :** Ow you mean Bondage Club version probably ^^

**Comment by Samael-dev** [comment]
That sad nothing exist for make an bot actually working, hope one day you will continue your project ~

**Comment by Kongchenglige** [comment]
Hope you can find what you want.
also hope one day I can back to the game and find joy in the game like in the old days.
❤️
